@startuml
User  --> Customer
Customer --> Agreement
Customer  --> Document
Customer  --> Case
Customer  --> Payment


User  --> Account
Account  --> Document
Account  --> Case
Account  --> Payment
Account --> Agreement

Customer -> Account

(User,Customer).. UserRole
UserRole .. (User,Account)
UserRole .. (Customer,Account)

Payment --> Collection
Payment --> Transaction

Agreement --> Policy
Policy -> Party
Policy --> Coverage
Policy --> InsurableObject

(Policy,Party) .. PolicyRole


@enduml
